[theme]
 primaryColor = "#1E88E5"
 backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#262730"
 font = "sans serif"
[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[deprecation]
showPyplotGlobalUse = false

[runner]
# Handle script rerun behavior
magicEnabled = true
fastReruns = true

[client]
# Enables more streamlined error display
showErrorDetails = true
toolbarMode = "auto" 